### ISSUE TITLE
Update Toy Data for tiltIndicator datasets after shifting emission profile's ranking function from tiltIndicatorBefore to tiltIndicator

### ISSUE THREAD

**Issue by kalashsinghal** [2DegreesInvesting/tiltToyData#20]
Relates to 2DegreesInvesting/tiltIndicator#644

**Comment by maurolepore** [comment]
Closing as it duplicates https://github.com/2DegreesInvesting/tiltToyData/issues/7 -- which is in review at
 https://github.com/2DegreesInvesting/tiltToyData/pull/19
