### ISSUE TITLE
Create a toy data set with financials

### ISSUE THREAD

**Issue by AnneSchoenauer** [2DegreesInvesting/tiltToyData#44]
Dear @kalashsinghal, 
For the Bundesbank project we need to run all our graphs on financial data. This data is highly sensitive and therefore we need to create a toy version of it. The Toy data would need to have the column: `bank_id`, `company_id`, `loan_amount`, `PoD`. What is important is that a bank could give multiple loans to different companies and that a company can receive loans from two different banks. An example can be found [here](https://docs.google.com/spreadsheets/d/1i4a_vGXTK2Zj_7MW528tEevUeQSPlqhJHl4xGg8MAMQ/edit#gid=28120548). 

Here are the following requirements: 

- [ ] We use all company_ids from the dataset that come out of the tiltIndicatorAfter package
- [ ] These companies can have loans from one or multiple banks
- [ ] A bank can also give two loans to the same company
- [ ] Let's have 10 banks in total 
- [ ] The amount_of total can out of simplicity a number between 0-1000
- [ ] A bank gives a probability_of_default to companies. This Probability of default is between 0-1. Mostly between 0-0.3. 
- [ ] If a bank gives to the same company a loan this company has the same probability of default, i.e. a bank only gives one probability of default to one company and not different ones. 
- [ ] It can be (and is very likely) that if a company gets two loans from different banks that the probabilty of default differs for the company. 

Could you provide such a dataset with the same company_id column that we use in our tilt Toy Datasets? 
Thanks a lot!
Best
Anne

**Comment by Tilmon** [comment]
@AnneSchoenauer until when do you need the data? It's the next task on @kalashsinghal 's list after the wrangling for Bundesbank is done, but would be good to know if you have any specific timeline in mind. Thanks!

**Comment by Tilmon** [comment]
@kalashsinghal, @Tilmon will share companies_id toyData with you. 
cc' @AnneSchoenauer
